#!/bin/bash

arch=$1
if [ "$arch" == "" ]; then
	echo pass architecture as 1st parameter
	exit 1
fi
dpkg-scanpackages . /dev/null dists/unstable/main/binary-$arch/ | tee Packages | gzip -9 > Packages.gz
# rpl "Filename: ." "Filename: dists/unstable/main/binary-i386" Packages
rm -rf unstable
rsync -av * homer:raine/html/archive/debian/dists/unstable/main/binary-$arch/
mkdir unstable && cd unstable && mkdir main && cd main && ln -s ../.. binary-$arch
cd ../.. 
apt-ftparchive -o APT::FTPArchive::Release::Suite=unstable -o APT::FTPArchive::Release::Label="Unofficial rainemu packages" -o APT::FTPArchive::Release::Architectures=$arch release unstable > ../Release
gpg --default-key B8C0220B --sign -ba -o ../Release.gpg ../Release \
rsync -av ../Release* homer:raine/html/archive/debian/dists/unstable/
