Document: raine
Title: Debian raine Manual
Author: <insert document author here>
Abstract: This manual describes what raine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/raine/raine.sgml.gz

Format: postscript
Files: /usr/share/doc/raine/raine.ps.gz

Format: text
Files: /usr/share/doc/raine/raine.text.gz

Format: HTML
Index: /usr/share/doc/raine/html/index.html
Files: /usr/share/doc/raine/html/*.html

  
